<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>preview</LangVersion>
		<RuntimeIdentifiers>win-x64;linux-x64;linux-arm64;osx-x64;osx-arm64</RuntimeIdentifiers>
	</PropertyGroup>

	<Choose>
		<When Condition="'$(RuntimeIdentifier)'==''">
			<ItemGroup Label="Native">
				<Content Include="runtimes/win-x64/native/libGDeflate.dll" PackagePath="runtimes/win-x64/native" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never"/>
				<Content Include="runtimes/linux-x64/native/libGDeflate.so" PackagePath="runtimes/linux-x64/native" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never"/>
				<Content Include="runtimes/linux-arm64/native/libGDeflate.so" PackagePath="runtimes/linux-arm64/native" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never"/>
				<Content Include="runtimes/osx-x64/native/libGDeflate.dylib" PackagePath="runtimes/osx-x64/native" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never"/>
				<Content Include="runtimes/osx-arm64/native/libGDeflate.dylib" PackagePath="runtimes/osx-arm64/native" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never"/>
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup Label="Native">
				<Content Include="runtimes/win-x64/native/libGDeflate.dll" Link="libGDeflate.dll" Condition="'$(RuntimeIdentifier)'=='win-x64'" CopyToOutputDirectory="Never" CopyToPublishDirectory="PreserveNewest"/>
				<Content Include="runtimes/linux-x64/native/libGDeflate.so" Link="libGDeflate.so" Condition="'$(RuntimeIdentifier)'=='linux-x64'" CopyToOutputDirectory="Never" CopyToPublishDirectory="PreserveNewest"/>
				<Content Include="runtimes/linux-arm64/native/libGDeflate.so" Link="libGDeflate.so" Condition="'$(RuntimeIdentifier)'=='linux-arm64'" CopyToOutputDirectory="Never" CopyToPublishDirectory="PreserveNewest"/>
				<Content Include="runtimes/osx-x64/native/libGDeflate.dylib" Link="libGDeflate.dylib" Condition="'$(RuntimeIdentifier)'=='osx-x64'" CopyToOutputDirectory="Never" CopyToPublishDirectory="PreserveNewest"/>
				<Content Include="runtimes/osx-arm64/native/libGDeflate.dylib" Link="libGDeflate.dylib" Condition="'$(RuntimeIdentifier)'=='osx-arm64'" CopyToOutputDirectory="Never" CopyToPublishDirectory="PreserveNewest"/>
			</ItemGroup>
		</Otherwise>
	</Choose>

</Project>
